---
title:  "Category Paths Analysis Summary"
author: "S. Aguinaga"
date:   "January 12, 2015"
output: html_document
---

<font color=#6495ED>PPR/SSSP/HumanPaths v CatPaths</font>
----------------------------------------------------------

<h3>Human Paths v Category Paths</h3>

For each game, the users that played each game are extracted and count the number of clicks for games started and finished.
Not all games were completed, but for those that were we can get the users that 
played a given game.

```{r, echo=FALSE}
# References
# http://www.cookbook-r.com/Manipulating_data/Converting_data_between_wide_and_long_format/
setwd('/home/saguinag/CategoryPaths/')
```

```{r, echo=FALSE}
library(ggplot2);library(reshape2)

# folder containing files showing paths and the shortest (SP) and CategoryPaths (CP) scores
hpcpsp_path = 'cat_ppr_DataFiles/kgcupscp.csv'
hpcpsp_dat <-read.csv(hpcpsp_path, na.strings ='inf')
#colClasses=c('clicks'='float','cp'='float',
#                                   'game'='factor','key'='factor',
#                                   'prob'='double','sp'='float','usr'='factor'
df <- data.frame(hpcpsp_dat)
ggplot(df, aes(x=cp, y=clicks)) +
    geom_point(alpha=.5,color = "cornflowerblue") + xlab('Category Paths (L)') + 
  ylab('Human Paths (L)') +
  scale_x_log10() + scale_x_log10() +ylim(0,150)
# data <- rbind(data,df)
# 
# all_dat <- melt(data);
# p0 <- ggplot(data,aes(cp,clicks))+geom_point(color="firebrick", alpha=.5,) + 
#   xlab('Category Path (L)') + ylab('Human Path (L)') + scale_x_log10() 
# p0

```

<h3>Shortest Paths vs Category Paths</h3>
The distribution of the shortest paths: single source shortest paths (sssp) for each games' end-points.
```{r, echo=FALSE}
# folder containing files showing paths and the shortest (SP) and CategoryPaths (CP) scores
cp_sp_path = 'ourAlgoScores/'
file.names <- list.files(cp_sp_path,pattern='*.csv')
data = data.frame()
for(i in 1:length(file.names)){
  cp_sp_dat <-read.csv(paste(cp_sp_path,file.names[i],sep = ''),
                       na.strings ='inf', 
                       colClasses=c('key'='factor','sp'='integer','cp'= 'integer'))
  df <- data.frame(cp_sp_dat)
  data <- rbind(data,df)
}
all_dat <- melt(data);
p1 <- ggplot(data,aes(cp,sp))+geom_point(color="firebrick", alpha=.5,) + xlab('Category Paths (L)') + ylab('SSSP (L)') + scale_x_log10() 
p1

```

<h3>Personal Page Rank</h3>

```{r, echo=FALSE}
hpcpsp_path = 'cat_ppr_DataFiles/kgcupscp.csv'
hpcpsp_dat <-read.csv(hpcpsp_path, na.strings ='inf')
#colClasses=c('clicks'='float','cp'='float',
#                                   'game'='factor','key'='factor',
#                                   'prob'='double','sp'='float','usr'='factor'
df <- data.frame(hpcpsp_dat)
ggplot(df, aes(x=cp, y=prob)) +
    geom_point(color = "cornflowerblue",alpha=.2) + xlab('Category Paths (L)') + 
  ylab('PPR (p)') + scale_y_log10() + scale_x_log10()

```



<font color=#6495ED>Difference between Human Paths</font>
----------------------------------------------------------
The following figure shows the raw difference between human paths, Cat paths, and SSSP.

```{r, echo=FALSE}

df$hpcpdelta<-(df$clicks - df$cp)
df$hpspdelta <- (df$clicks -df$sp)
head(df)

#qplot(hpcpdelta, data=df,geom="line")
# p3<-qplot(seq_along(df$hpcpdelta), df$hpcpdelta, geom="path",color='hp-cp') 
# p3<-qplot(seq_along(df$hpspdelta), df$hpspdelta, geom="path",color='hp-sp') 
# p3
# Multiple plot function
#
# ggplot objects can be passed in ..., or to plotlist (as a list of ggplot objects)
# - cols:   Number of columns in layout
# - layout: A matrix specifying the layout. If present, 'cols' is ignored.
#
# If the layout is something like matrix(c(1,2,3,3), nrow=2, byrow=TRUE),
# then plot 1 will go in the upper left, 2 will go in the upper right, and
# 3 will go all the way across the bottom.
#
multiplot <- function(..., plotlist=NULL, file, cols=1, layout=NULL) {
  require(grid)

  # Make a list from the ... arguments and plotlist
  plots <- c(list(...), plotlist)

  numPlots = length(plots)

  # If layout is NULL, then use 'cols' to determine layout
  if (is.null(layout)) {
    # Make the panel
    # ncol: Number of columns of plots
    # nrow: Number of rows needed, calculated from # of cols
    layout <- matrix(seq(1, cols * ceiling(numPlots/cols)),
                    ncol = cols, nrow = ceiling(numPlots/cols))
  }

 if (numPlots==1) {
    print(plots[[1]])

  } else {
    # Set up the page
    grid.newpage()
    pushViewport(viewport(layout = grid.layout(nrow(layout), ncol(layout))))

    # Make each plot, in the correct location
    for (i in 1:numPlots) {
      # Get the i,j matrix positions of the regions that contain this subplot
      matchidx <- as.data.frame(which(layout == i, arr.ind = TRUE))

      print(plots[[i]], vp = viewport(layout.pos.row = matchidx$row,
                                      layout.pos.col = matchidx$col))
    }
  }
}

p0 <- qplot(seq_along(hpcpdelta), hpcpdelta, data = df, geom = "path") 
p0 <- p0+labs(x="",y="Human - Cat Paths",title="Raw Difference")
p1 <- qplot(seq_along(hpspdelta), hpspdelta, data = df, geom = "path")
p1 <- p1+labs(x="Games", y="Human - SSS Paths")
multiplot(p0,p1, cols=1)
```

Percent Difference between Human Paths vs. Category Paths, and Human Paths vs. SSSP.

```{r, echo=FALSE}
#boxplot(df$hpcpdelta~df$hpspdelta)
## http://msemac.redwoods.edu/~darnold/math15/spring2013/R/Activities/BoxplotsII.html
# with(df,{
#   boxplot(hpcpdelta,hpspdelta,
#           names=c("cat path","sss path"),
#           col=c("turquoise","tomato"),
#           xlab="Difference from Human Paths",
#           main="Plot 2") 
# })
# hpcp<-df$hpcpdelta
# hpsp<-df$hpspdelta
require("Rmisc")
#ds <- data.frame(catpath=hpcp,sssp=hpsp) 
ds.1 <-summarySE( df, measurevar="hpcpdelta", na.rm=TRUE)
colnames(ds.1)[3] <- "differ"

ds.2 <-summarySE( df, measurevar="hpspdelta", na.rm=TRUE)
colnames(ds.2)[3] <- "differ"

data <- rbind(ds.1, ds.2)
# aes(x=pathdelta, y=pctdiff, colour=pathdelta, group=pathdelta, fill=pathdelta, shape=pathdelta)
# as.factor(N)
plta <- ggplot(data, aes(x = as.factor(N), y=differ)) +
  geom_point(size=6) + geom_errorbar(aes(ymin=data$differ-data$se, ymax=data$differ + data$se, width=0.25), color="red") +
  geom_errorbar(aes(ymin=data$differ-data$ci, ymax=data$differ + data$ci, width=0.35), color="black") + 
  scale_y_continuous(limits=c(0,5), breaks=c(0:5)) + 
  theme_classic() + scale_x_discrete(labels=c("Human Path -\nCatPath","Human Path -\nShortest Path")) + 
  xlab("") + ylab("Mean Difference") + 
  theme(legend.position="None",
                  # Text settings for scale
                  axis.text = element_text(size=12),
                  # Text settings for axis titles
                  axis.title.y = element_text(size=16),
                  axis.title.x = element_text(size=16))
plta
ggsave(plta, file="plotFiles/figure_diff.pdf",width=5, height=4)




# ds <- data.frame(sp=df$sp,hp=df$clicks, cp=df$cp)
# ## Next, compute the pct diff b/w hp-cp, hp-sp
# ds <- transform(ds, hp_v_cp = (hp-sp)/((hp+sp)/2)*100, hp_v_sp = (hp-cp)/((hp+cp)/2)*100)
# 
# ## Reshape into long format, from {SO}/questions/16896632
# ds_long <- reshape2:::melt.data.frame(ds,
#                 id.vars=c("sp","hp","cp"),
#                 measure.vars=c("hp_v_cp","hp_v_sp"),
#                 variable.name=c("pathdelta"),
#                 value.name="pctdiff"
#                 ) 
# head(ds_long)
# tail(ds_long)
```

```{r, echo=FALSE}
## Summarizes data.
## Gives count, mean, standard deviation, standard error of the mean, and confidence interval (default 95%).
##   data: a data frame.
##   measurevar: the name of a column that contains the variable to be summariezed
##   groupvars: a vector containing names of columns that contain grouping variables
##   na.rm: a boolean that indicates whether to ignore NA's
##   conf.interval: the percent range of the confidence interval (default is 95%)
# summarySE <- function(data=NULL, measurevar, groupvars=NULL, na.rm=FALSE,
#                       conf.interval=.95, .drop=TRUE) {
#     require(plyr)
# 
#     # New version of length which can handle NA's: if na.rm==T, don't count them
#     length2 <- function (x, na.rm=FALSE) {
#         if (na.rm) sum(!is.na(x))
#         else       length(x)
#     }
# 
# 
#     # This does the summary. For each group's data frame, return a vector with
#     # N, mean, and sd
#     datac <- ddply(data, groupvars, .drop=.drop,
#       .fun = function(xx, col) {
#         c(N    = length2(xx[[col]], na.rm=na.rm),
#           mean = mean   (xx[[col]], na.rm=na.rm),
#           sd   = sd     (xx[[col]], na.rm=na.rm)
#         )
#       },
#       measurevar
#     )
#     # Rename the "mean" column    
#     datac <- rename(datac, c("mean" = measurevar))
# 
#     datac$se <- datac$sd / sqrt(datac$N)  # Calculate standard error of the mean
# 
#     # Confidence interval multiplier for standard error
#     # Calculate t-statistic for confidence interval: 
#     # e.g., if conf.interval is .95, use .975 (above/below), and use df=N-1
#     ciMult <- qt(conf.interval/2 + .5, datac$N-1)
#     datac$ci <- datac$se * ciMult
# 
#     return(datac)
# } ## inlcude Hmisc, Rmisc
#require("Rmisc")
## Summary statistics including SEM & CI
# dfc <- summarySE(ds_long, measurevar="pctdiff",groupvars=c("pathdelta"), na.rm=TRUE)
# dfc
# ## Plot of means with error bars
# plot2a <- ggplot(dfc, aes(x=pathdelta, y=pctdiff, colour=pathdelta, group=pathdelta, fill=pathdelta, shape=pathdelta)) + geom_errorbar(aes(ymin=pctdiff-ci, ymax=pctdiff+ci), colour="black", width=.1) + geom_errorbar(aes(ymin=pctdiff-se, ymax=pctdiff+se), colour="red", width=.1) + geom_point(size=3)+scale_y_log10() + xlab("Path Length Compared") + ylab("Percent Difference (%)") + ggtitle("Difference from Human Paths") 
# plot2a
```

<font color=#6495ED>3 Category vs Human Path Length</font>
---------------------------------------------------------
```{r,echo=FALSE}
hpcpsp_path = 'cat_ppr_DataFiles/kgcupscp.csv'
data_path   = 'pathsHopsFiles/kgcupscp_ppr_hops.csv'
hpcpsp_dat <-read.csv(data_path, na.strings ='inf')
require("Rmisc")
dfc  <- data.frame()
dfc  <- summarySE(hpcpsp_dat, measurevar="cp",groupvars=c("clicks"), na.rm=TRUE)
#head(dfc)
#tail(dfc)

plt9 <- ggplot(dfc, aes(x=clicks, y=cp)) + 
  geom_errorbar(aes(ymin=cp-ci, ymax=cp+ci), colour="black", width=0.4) + 
  geom_errorbar(aes(ymin=cp-se, ymax=cp+se), colour="red",   width=0.4) + 
  geom_point(size=2) +xlim(0,30) + ylim(3,10) + ylab("Category Length (L)")+
  theme_classic() + 
  theme(legend.key.width=unit(2,"line"),
        # Text settings for scale
        axis.text = element_text(size=12),
        # Text settings for axis titles
        axis.title.y = element_text(size=18),
        axis.title.x = element_text(size=18) 
        )

#
plt9

```


<font color=#6495ED>Hops to Go</font>
----------------------------------------------------------

```{r,echo=FALSE}
hpcpsp_path = 'cat_ppr_DataFiles/kgcupscp.csv'
hpcpsp_df <-read.csv(hpcpsp_path, na.strings ='inf')
# dim(hpcpsp_df)
# require(dplyr)
# togo <- group_by(hpcpsp_df,clicks)
# head(togo)

```



